[run]
    concurrency = 4
    tests = false

[linters-settings]
    [linters-settings.gocyclo]
        min-complexity = 20

    [linters-settings.goconst]
        min-len = 2
        min-occurrences = 2

    [linters-settings.misspell]
        locale = "US"

[issues]
    exclude-use-default = false

[linters]
    # White-listing, to be more CI safe.
    disable-all = true

    # @see https://github.com/golangci/golangci-lint#enabled-by-default-linters
    enable = [
        "copyloopvar",
        "dupl",
        "depguard",
        "errcheck",
        "ginkgolinter",
        "goconst",
        "gocyclo",
        "gofmt",
        "gocritic",
        "goimports",
        "gosec",
        "gosimple",
        "govet",
        "ineffassign",
        "lll",
        "misspell",
        "nakedret",
        "prealloc",
        "revive",
        "staticcheck",
        "stylecheck",
        "typecheck",
        "unconvert",
        "unparam",
        "unused",
    ]

[linters-settings.depguard.rules.main]
allow = [
    "$gostd",
    "github.com/bytedance/gopkg",
    "github.com/h2non/bimg",
    "github.com/h2non/filetype",
    "github.com/prometheus/client_golang",
    "github.com/quic-go/quic-go",
    "github.com/rs/cors",
    "github.com/throttled/throttled",
    "golang.org/x/sys/unix"
]

[linters-settings.revive]
rules = [
    { name = "comment-spacings" }
]