name: CI

on:
  create:
  push:
    branches:
      - "**"
    tags:
      - "*"
    paths-ignore:
      - ".dockerignore"
      - ".github/CODEOWNERS"
      - ".github/dependabot.yml"
      - ".github/workflows/clean-old-runs.yml"
      - ".github/workflows/codeql.yml"
      - ".github/workflows/dependency-review.yml"
      - ".github/workflows/docker.yml"
      - ".github/workflows/scorecard.yml"
      - ".gitignore"
      - ".golangci.toml"
      - "benchmark.sh"
      - "History.md"
      - "LICENSE"
      - "Makefile"
      - "README.md"
      - "SECURITY.md"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: stable
      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get dist-upgrade -y && \
          sudo apt-get install --no-install-recommends -y \
              automake \
              build-essential \
              ca-certificates \
              curl \
              gobject-introspection \
              gtk-doc-tools \
              libcfitsio-dev \
              libexif-dev \
              libfftw3-dev \
              libgif-dev \
              libglib2.0-dev \
              libgsf-1-dev \
              libheif-dev \
              libimagequant-dev \
              libjpeg-turbo8-dev \
              libmagickwand-dev \
              libmatio-dev \
              libopenslide-dev \
              liborc-0.4-dev \
              libpango1.0-dev \
              libpng-dev \
              libpoppler-glib-dev \
              librsvg2-dev \
              libtiff-dev \
              libvips-dev \
              libwebp-dev \
              libxml2-dev \
              swig
        env:
          DEBIAN_FRONTEND: noninteractive
      - name: Test
        run: go test ./... -test.v -test.coverprofile=atomic .

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: stable
      - name: Install dependencies
        run: |
          sudo apt update && \
          sudo apt-get dist-upgrade -y && \
          sudo apt-get install --no-install-recommends -y \
              automake \
              build-essential \
              ca-certificates \
              curl \
              gobject-introspection \
              gtk-doc-tools \
              libcfitsio-dev \
              libexif-dev \
              libfftw3-dev \
              libgif-dev \
              libglib2.0-dev \
              libgsf-1-dev \
              libheif-dev \
              libimagequant-dev \
              libjpeg-turbo8-dev \
              libmagickwand-dev \
              libmatio-dev \
              libopenslide-dev \
              liborc-0.4-dev \
              libpango1.0-dev \
              libpng-dev \
              libpoppler-glib-dev \
              librsvg2-dev \
              libtiff-dev \
              libvips-dev \
              libwebp-dev \
              libxml2-dev \
              swig
        env:
          DEBIAN_FRONTEND: noninteractive
      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          args: --timeout=30m --config=.golangci.toml --issues-exit-code=255
          version: latest

  fuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: stable
      - name: Install dependencies
        run: |
          sudo apt update && \
          sudo apt-get dist-upgrade -y && \
          sudo apt-get install --no-install-recommends -y \
              automake \
              build-essential \
              ca-certificates \
              curl \
              gobject-introspection \
              gtk-doc-tools \
              libcfitsio-dev \
              libexif-dev \
              libfftw3-dev \
              libgif-dev \
              libglib2.0-dev \
              libgsf-1-dev \
              libheif-dev \
              libimagequant-dev \
              libjpeg-turbo8-dev \
              libmagickwand-dev \
              libmatio-dev \
              libopenslide-dev \
              liborc-0.4-dev \
              libpango1.0-dev \
              libpng-dev \
              libpoppler-glib-dev \
              librsvg2-dev \
              libtiff-dev \
              libvips-dev \
              libwebp-dev \
              libxml2-dev \
              swig
        env:
          DEBIAN_FRONTEND: noninteractive
      - name: fuzzing
        run: ./run-fuzz-tests.sh 15s

  docker:
    needs:
      - fuzz
      - lint
      - test
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      branch: ${{ github.ref_name }}
      commit: ${{ github.sha }}
